name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies and build
        run: |
          yarn
          yarn build
      - name: Deploy via SCP
        env:
          TARGET_DIR: ${{ secrets.PATH_TO_DEPLOY }} # Укажите путь к папке на сервере
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          rsync -avz -e "ssh -i private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" ./dist/ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:$TARGET_DIR
          rm -f private_key
